# coding=utf-8
#CODIGO DE LA REGLA DE CALIDAD: CLI_42_002
#GLOSA: EVALUA SI LA FECHA DEL INGRESADA ES MENOR O IGUAL QUE LA FECHA DE LOS DATOS
#COMPLEJIDAD: BAJA (porque aplica a solo un EDC)
#PROBADO EN Pyspark
#FECHA MODIFICACION: 018/07/2018
#AUTOR: FELIPE ÁVALOS DÍAZ

def CLI_42_002(YEAR,MONTH,DAY,FILE_DATE):
    DATE = YEAR+MONTH+DAY
    if DATE <= FILE_DATE:
        return 1
    else:
        return 0